name: Generate Pac-Man animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: generate pac-man.svg
        uses: Platane/snk@v3
        with:
          github_user_name: koopatroopa787
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=%23ffdd44&color_dots=%23ff6b6b
            
      - name: push pac-man.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
